//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogonAcceptanceWindow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Windows10Theme {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Windows10Theme() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogonAcceptanceWindow.Windows10Theme", typeof(Windows10Theme).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF005A9E.
        /// </summary>
        internal static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFB2D5F4.
        /// </summary>
        internal static string Btn_BorderColor {
            get {
                return ResourceManager.GetString("Btn.BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF79B0D8.
        /// </summary>
        internal static string Btn_BorderHoverColor {
            get {
                return ResourceManager.GetString("Btn.BorderHoverColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF2C628B.
        /// </summary>
        internal static string Btn_BorderMouseDownColor {
            get {
                return ResourceManager.GetString("Btn.BorderMouseDownColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF337BB1.
        /// </summary>
        internal static string Btn_Color {
            get {
                return ResourceManager.GetString("Btn.Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF357AAF.
        /// </summary>
        internal static string Btn_HoverColor {
            get {
                return ResourceManager.GetString("Btn.HoverColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF00427D.
        /// </summary>
        internal static string Btn_MouseDownColor {
            get {
                return ResourceManager.GetString("Btn.MouseDownColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFFFF.
        /// </summary>
        internal static string Btn_TextColor {
            get {
                return ResourceManager.GetString("Btn.TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFFFF.
        /// </summary>
        internal static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
    }
}
